theme = "doom_acario_dark"



[editor]
clipboard-provider = "win32-yank"
bufferline = "always"
auto-format = true
mouse = false
line-number = "relative"

[editor.file-picker]
git-ignore = true

[editor.cursor-shape]
# insert = "bar"
# select = "underline"
