theme = "doom_acario_dark"

[editor.clipboard-provider.custom]
yank = { command = "clip.exe" }
paste = { command = "powershell.exe", args = ["-command", "Get-Clipboard | Out-String"] }



[editor]
bufferline = "always"
auto-format = true
mouse = false
line-number = "relative"

[editor.file-picker]
git-ignore = false

[editor.cursor-shape]
# insert = "bar"
# select = "underline"
